[package]
name = "tcp-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
tokio = { version = "1.40.0", features = [
    "io-util",
    "io-std",
    "net",
    "rt",
    "rt-multi-thread",
    "macros",
] }
